<?php 
	/**********************************************************
	 **** File generated by fitzlucassen\DALGenerator tool ****
	 * All right reserved to fitzlucassen repository on github*
	 ************* https://github.com/fitzlucassen ************
	 **********************************************************/
	namespace fitzlucassen\FLFramework\Data\Base\Entity;

	use fitzlucassen\FLFramework\Library\Core;
	use fitzlucassen\FLFramework\Data\Entity;

	class Base  {
		private $_queryBuilder;

		public function __construct(){
			$this->_queryBuilder = new Core\QueryBuilder(true);
			$this->fillObject(array());
		}

		/***********
		 * GETTERS *
		 ***********/
		/*******
		 * END *
		 *******/

		public function fillObject($properties) {
		}
	}
