<?php 
	/**********************************************************
	 **** File generated by fitzlucassen\DALGenerator tool ****
	 * All right reserved to fitzlucassen repository on github*
	 ************* https://github.com/fitzlucassen ************
	 **********************************************************/
	namespace fitzlucassen\FLFramework\Data\Base\Entity;

	use fitzlucassen\FLFramework\Library\Core;
	use fitzlucassen\FLFramework\Data\Entity;

	class NewsBase  {
		private $_id;
		private $_title;
		private $_description;
		private $_creationDate;
		private $_fromCompany;
		private $_queryBuilder;

		public function __construct($id = '', $title = '', $description = '', $creationDate = '', $fromCompany = ''){
			$this->_queryBuilder = new Core\QueryBuilder(true);
			$this->fillObject(array("id" => $id, "title" => $title, "description" => $description, "creationDate" => $creationDate, "fromCompany" => $fromCompany));
		}

		/***********
		 * GETTERS *
		 ***********/
		public function getId() {
			return $this->_id;
		}
		public function getTitle() {
			return $this->_title;
		}
		public function getDescription() {
			return $this->_description;
		}
		public function getCreationDate() {
			return $this->_creationDate;
		}
		public function getFromCompany() {
			return $this->_fromCompany;
		}
		/*******
		 * END *
		 *******/

		public function fillObject($properties) {
			if(!empty($properties["id"]))
				$this->_id = $properties["id"];
			if(!empty($properties["title"]))
				$this->_title = $properties["title"];
			if(!empty($properties["description"]))
				$this->_description = $properties["description"];
			if(!empty($properties["creationDate"]))
				$this->_creationDate = $properties["creationDate"];
			if(!empty($properties["fromCompany"]))
				$this->_fromCompany = $properties["fromCompany"];
		}
	}
