<?php

/**********************************************************
 **** File generated by fitzlucassen\DALGenerator tool ****
 * All right reserved to fitzlucassen repository on github*
 ************* https://github.com/fitzlucassen ************
 **********************************************************/

namespace fitzlucassen\FLFramework\Data\Repository;

use fitzlucassen\FLFramework\Library\Core;
use fitzlucassen\FLFramework\Data\Entity;
use fitzlucassen\FLFramework\Data\Base\Entity as EntityBase;
use fitzlucassen\FLFramework\Data\Base\Repository as RepositoryBase;

class CocktailcocktailcategoriesRepository extends RepositoryBase\CocktailcocktailcategoriesRepositoryBase
{
	public function __construct($pdo, $lang)
	{
		parent::__construct($pdo, $lang);
	}

	public function updateCategoryName($id, $name)
	{
		$query = $this->_queryBuilder->update("cocktailcocktailcategories", array('name' => $name))->where(array(array("link" => "", "left" => "id", "operator" => "=", "right" => $id)))->getQuery();
		try {
			return $this->_pdo->Query($query);
		} catch (PDOException $e) {
			print $e->getMessage();
		}
		return array();
	}
}
